package Network;
public enum MessageType {
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    NEW_GAME_REQUEST,
    NEW_GAME_RESPONSE,
    JOIN_GAME_REQUEST,
    JOIN_GAME_RESPONSE,
    CREATE_GAME,
    WAIT_PLAYERS,
    STARTING_GAME,
    CURRENT_PLAYER,
    PING_MESSAGE,
    MATCH_PHASE,
    ERROR,
    WIN_MESSAGE,
    DISCONNECTION,
    END_MATCH
}